# Basic Information
title: Yujun Cai
position: Research Scientist
affiliation: Meta Reality Lab
affiliation_link: https://cs.jhu.edu/
email: yujun001 (at) e.ntu.edu.sg

# Search Engine Optimization (SEO)
keywords: yujun cai, cai yujun, yujuncai, caiyujun
canonical: https://www.cs.jhu.edu/~yyliu/
description: Yujun Cai is a Research Scientist in Meta Reality Lab. Her research lies in computer vision, graph learning and natural language processing.

# The option is used to enable the Johns Hopkins template.
enable_hopkins_logo: true

# The option is used to show the last update time.
enable_last_update: false

# Links
google_scholar: https://scholar.google.com.sg/citations?user=TE7lbQwAAAAJ&hl=en
cv_link: https://files.yliu.me/Yaoyao_Liu_Curriculum_Vitae.pdf
# github_link: https://github.com/yaoyao-liu/
linkedin: https://www.linkedin.com/in/yujuncai/
# twitter: https://twitter.com/YaoyaoLiu1/

# Images
avatar: https://img.yliu.me/avatar.jpg
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png

# Footnotes
footnote: Feel free to use my website's source code.
footnote_link: https://github.com/yaoyao-liu/minimal-light

# Analytics
# Please remove the following lines about analytics services if you fork my project.
# Otherwise, the analytics information of your website will be recorded to my ClustrMaps accounts.
clustrmaps_id: l3lesztPwCz-uXlzFI1Lt9SB3Ctz-pBQuMdYqnD0Ul8

# The following files will be removed from the generated website.
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - CNAME
