# Basic Information 
title: Yujun Cai
position: Research Scientist
affiliation: Meta
# affiliation_link: https://web.cs.ucla.edu/~kwchang/members/
email: vanora.caiyj@gmail.com / yujun001@e.ntu.edu.sg

# Search Engine Optimization (SEO)
# keywords: yiwei wang, wang yiwei, nus, ucla, amazon, natural language processing, graph neural networks
canonical: https://vanoracai.github.io/
description: Yujun Cai is a Research Scientist in Meta Reality Lab. Her research lies in computer vision, graph learning and natural language processing.

# The option is used to enable the Johns Hopkins template.
enable_hopkins_logo: true

# The option is used to show the last update time.
enable_last_update: true

# Links
google_scholar: https://scholar.google.com.sg/citations?user=TE7lbQwAAAAJ&hl=en
cv_link: ./yujun_cv_2024_0926.pdf
# github_link: https://github.com/yaoyao-liu/
linkedin: https://www.linkedin.com/in/yujuncai/
# twitter: https://twitter.com/wangyiw33973985

# Images 
avatar: ./photo.png
favicon: ./assets/img/450.png
favicon_dark: ./assets/img/450.png

# The following files will be removed from the generated website.
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - CNAME
